#!/bin/bash
#
# handover-hangover watchdog
#
# Guarantees a handoff note exists for the incoming model, even if
# the previous model didn't follow prompt instructions.
#
# Runs at the start of every turn, before the model receives control.
# Execution order: handoff.sh -> anchor.sh -> model
#
# Three scenarios:
#   1. handoff-note.md exists        -> previous model wrote it (CONFIRMED)
#      No signal — model was healthy. Archive only.
#   2. no note, but .prev.md exists  -> DIRTY SWITCH (model failed to write)
#      Creates .handoff-pending signal for the incoming model.
#   3. no note, no .prev.md          -> INIT (first run ever)
#      Creates .handoff-pending signal for the incoming model.
#

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

WORKSPACE="${WORKSPACE:-$(cd "$(dirname "$0")/../../.." && pwd)}"
MEMORY_DIR="$WORKSPACE/memory"
HANDOFF_NOTE="$MEMORY_DIR/handoff-note.md"
HANDOFF_PREV="$MEMORY_DIR/handoff-note.prev.md"
HANDOFF_SIGNAL="$MEMORY_DIR/.handoff-pending"
CURRENT_TASK="$MEMORY_DIR/current-task.md"
LOG_PREFIX="[handover-hangover]"

mkdir -p "$MEMORY_DIR"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

timestamp() {
    date -u '+%Y-%m-%dT%H:%M:%SZ'
}

log() {
    echo "$LOG_PREFIX $1"
}

# Collect files modified in the last 30 minutes (workspace, depth 3).
# Excludes .git, node_modules, and the handoff-note itself.
recent_changes() {
    find "$WORKSPACE" -maxdepth 3 -type f \
        \( -name "*.md" -o -name "*.sh" -o -name "*.ts" -o -name "*.js" \
           -o -name "*.py" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) \
        -mmin -30 \
        ! -path "*/.git/*" \
        ! -path "*/node_modules/*" \
        ! -name "handoff-note.md" \
        ! -name "handoff-note.prev.md" \
        2>/dev/null | sort | while IFS= read -r f; do
        echo "  - ${f#"$WORKSPACE/"}"
    done
}

# Read the first few lines of current-task.md, or a placeholder.
read_current_task() {
    if [ -f "$CURRENT_TASK" ]; then
        head -n 5 "$CURRENT_TASK" 2>/dev/null || echo "(error reading current-task.md)"
    else
        echo "(no current-task.md found — this is a fresh start)"
    fi
}

# Short git status, or a placeholder.
read_git_status() {
    if command -v git >/dev/null 2>&1 \
       && git -C "$WORKSPACE" rev-parse --git-dir >/dev/null 2>&1; then
        local status
        status=$(git -C "$WORKSPACE" status --short 2>/dev/null) || true
        if [ -z "$status" ]; then
            echo "(clean working tree)"
        else
            echo "$status"
        fi
    else
        echo "(not a git repo or git unavailable)"
    fi
}

# ---------------------------------------------------------------------------
# Fallback note generator
# ---------------------------------------------------------------------------

generate_fallback() {
    local reason="$1"

    local task
    task=$(read_current_task)

    local files
    files=$(recent_changes)
    [ -z "$files" ] && files="  (no files modified in the last 30 minutes)"

    local gitstatus
    gitstatus=$(read_git_status)

    # Trim reason to the first sentence for the footer tag
    local short_reason="${reason%%.*}"

    cat > "$HANDOFF_NOTE" <<EOF
# Handoff Note

## Why you are here
${reason}

## Current task
${task}

## Current mode
unknown (script-generated fallback)

## Confidence
unknown

## What was already done
(not available — script-generated)

## What was checked and ruled out
(not available — script-generated)

## Tool state
- recently modified files:
${files}
- git status:
${gitstatus}

## Next step
Read this handoff-note and memory/current-task.md before continuing.

## Do not assume
- prior assistant thoughts are yours
- current task is complete
- tool state survived
- you were already in the correct mental mode

--- generated by scripts/handoff.sh (${short_reason}) at $(timestamp)
EOF
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# Clean up stale signal from previous turn (model should have deleted it,
# but if it didn't, we don't want it lingering as a false positive).
rm -f "$HANDOFF_SIGNAL"

if [ -f "$HANDOFF_NOTE" ]; then
    # Previous model wrote a handoff note — archive it for the next model.
    # No signal: CONFIRMED means the model was functioning normally.
    # If a switch happened despite the note existing, Indicators 2/3
    # in SKILL.md (context mismatch / error signals) will catch it.
    log "model-written handoff confirmed"
    mv -f "$HANDOFF_NOTE" "$HANDOFF_PREV"

elif [ -f "$HANDOFF_PREV" ]; then
    # No note but .prev.md exists — the model failed to write (DIRTY SWITCH).
    # Signal the incoming model: this is an anomaly requiring read-side.
    log "WARNING: dirty switch — no handoff-note found, generating fallback"
    generate_fallback "Possible model switch or continuity break. Previous model did not write a handoff note. Data below is mechanical only."
    mv -f "$HANDOFF_NOTE" "$HANDOFF_PREV"
    touch "$HANDOFF_SIGNAL"

else
    # No note, no prev — first time this skill runs (INIT).
    # Signal the incoming model to run bootstrap.
    log "INIT: first run, creating bootstrap note"
    generate_fallback "First run of Handover Hangover. No prior handoff history."
    mv -f "$HANDOFF_NOTE" "$HANDOFF_PREV"
    touch "$HANDOFF_SIGNAL"
fi
